
stack = []
stack.append(5)
stack.append(3)
stack.pop(-1)
stack.append(2)
stack.append(8)
stack.pop(-1)
stack.pop(-1)
stack.append(9)
stack.append(1)
stack.pop(-1)
stack.append(7)
stack.append(6)
stack.pop(-1)
stack.pop(-1)
stack.append(4)
stack.pop(-1)
stack.pop(-1)
print(stack)